name: Hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@main
